services:
  postgresql:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '15432:5432'
    restart: always
  postgresql-pgadmin:
    image: 'dockage/phppgadmin'
    environment:
      PHP_PG_ADMIN_SERVER_HOST: 'postgresql'
      PHP_PG_ADMIN_SERVER_PORT: '5432'
      PHP_PG_ADMIN_SERVER_USER: 'postgres'
      PHP_PG_ADMIN_SERVER_PASSWORD: 'root'
    ports:
      - '8002:80'
    restart: always
  tarantool:
    image: 'tarantool/tarantool:2'
    ports:
      - '13301:3301'
    restart: always
  tarantool-admin:
    image: quay.io/basis-company/tarantool-admin
    environment:
      TARANTOOL_CONNECTIONS: 'tarantool'
    ports:
      - '8000:80'
    restart: always