services:
  postgresql:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '15432:5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  tarantool:
    image: 'tarantool/tarantool:2'
    ports:
      - '13301:3301'
    restart: always
