services:
  postgresql:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '15432:5432'
    restart: always
  tarantool:
    image: 'tarantool/tarantool:2'
    ports:
      - '13301:3301'
    restart: always
