name: coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: xdebug
          tools: phpunit, composer:v2
      - run: docker compose up -d --quiet-pull
      - run: composer install
      - run: vendor/bin/phpunit
      - run: cat ./coverage.txt