name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.3", "8.4"]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
      - run: docker compose up -d --quiet-pull
      - run: dockerize -wait tcp://127.0.0.1:15432 -timeout 30s
      - run: vendor/bin/phpunit tests --no-coverage
